// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfygubqrlukyqqnncnih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeWd1YnFybHVreXFxbm5jbmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTQxMjAsImV4cCI6MjA2NjA5MDEyMH0.LUMeCCaSwBkpHB1cSczYN2M-zSyhVkxEAkNob2CfHF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);